# Generated by Django 4.1.3 on 2022-11-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='Name',
            new_name='FirstName',
        ),
        migrations.AddField(
            model_name='members',
            name='Email',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='LastName',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='PhoneNumber',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
