# Generated by Django 4.1.3 on 2022-11-10 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_name_members_firstname_members_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
